const AUTH_ACTIONS = {
  CLEAR: 'CLEAR_AUTH',
  SET_ADDRESS_FIXED_STATUS: 'SET_ADDRESS_FIXED_STATUS',
  SET_EMAIL_VALIDATION_STATUS: 'SET_EMAIL_VALIDATION_STATUS',
  SET_FINISHED_CONFIGURATION_STATUS: 'SET_FINISHED_CONFIGURATION_STATUS',
  SET_TOKENS: 'SET_TOKENS',
  SET_TOS_ACCEPTANCE_REQUIRED_STATUS: 'SET_TOS_ACCEPTANCE_REQUIRED_STATUS',
  SET_USER_DATA: 'SET_USER_DATA'
};

const CASHBUZZ_ACTIONS = {
  CLEAR: 'CLEAR_CASHBUZZ',
  SET_ATTRIBUTES: 'SET_ATTRIBUTES',
  SET_CASHBUZZ_CLASSES: 'SET_CASHBUZZ_CLASSES',
  SET_CASHBUZZ_POLICY: 'SET_CASHBUZZ_POLICY',
  SET_CASHBUZZ_QCLASSES: 'SET_CASHBUZZ_QCLASSES',
  SET_ENFORCE_ACCOUNT_STATUS: 'SET_ENFORCE_ACCOUNT_STATUS'
};

export { AUTH_ACTIONS, CASHBUZZ_ACTIONS };
